    /* CREACIÓN DE LAS TABLAS */
    
    create table conserje (
        id bigint generated by default as identity,
        apellido varchar(255),
        contrasenia varchar(255),
        nombre varchar(255),
        usuario varchar(255),
        primary key (id)
    );

    create table direccion (
        id bigint generated by default as identity,
        calle varchar(255),
        codigo_postal varchar(255),
        departamento varchar(255),
        localidad varchar(255),
        numero varchar(255),
        pais varchar(255),
        piso varchar(255),
        provincia varchar(255),
        primary key (id)
    );

    create table factura (
        importe_total float(53),
        fecha_de_emision timestamp(6),
        id bigint generated by default as identity,
        reserva_id bigint unique,
        tipo varchar(255) check (tipo in ('A','B')),
        primary key (id)
    );

    create table habitacion (
        numero integer not null,
        tipo_habitacion_id bigint not null,
        estado varchar(255) not null check (estado in ('OCUPADA','RESERVADA','LIBRE','EN_MANTENIMIENTO')),
        primary key (numero)
    );

    create table item_factura (
        cantidad integer,
        precio_unitario float(53),
        subtotal float(53),
        factura_id bigint not null,
        id bigint generated by default as identity,
        descripcion varchar(255),
        primary key (id)
    );

    create table nota_de_credito (
        monto float(53),
        fecha_realizacion timestamp(6),
        id bigint generated by default as identity,
        idnota varchar(255) unique,
        primary key (id)
    );

    create table pago (
        monto_acumulado float(53),
        vuelto float(53),
        fecha_de_realizacion timestamp(6),
        id bigint generated by default as identity,
        primary key (id)
    );

    create table pasajero (
        direccion_id bigint,
        fecha_de_nacimiento timestamp(6),
        id bigint generated by default as identity,
        apellido varchar(255),
        cuit varchar(255),
        email varchar(255),
        estado varchar(255) check (estado in ('ACTIVO','INACTIVO')),
        nacionalidad varchar(255),
        nombre varchar(255),
        nro_documento varchar(255),
        ocupacion varchar(255),
        telefono varchar(255),
        primary key (id)
    );

    create table reserva (
        habitacion_id integer not null,
        fecha_egreso timestamp(6),
        fecha_ingreso timestamp(6),
        id bigint generated by default as identity,
        responsable_id bigint not null,
        primary key (id)
    );

    create table tipo_habitacion (
        cantidad_disponible integer not null,
        costo_por_noche numeric(38,2) not null,
        id bigint generated by default as identity,
        nombre varchar(255) not null unique,
        primary key (id)
    );

    alter table if exists factura 
       add constraint FKg69rrgpy99eypr8n2sdv1ln7r 
       foreign key (reserva_id) 
       references reserva;

    alter table if exists habitacion 
       add constraint FKtfvub72ms09yb6me9na7fdmjm 
       foreign key (tipo_habitacion_id) 
       references tipo_habitacion;

    alter table if exists item_factura 
       add constraint FKkfblphnv8cfyocr7pvaf613v7 
       foreign key (factura_id) 
       references factura;

    alter table if exists pasajero 
       add constraint FK7g85q38602vucpn0hwg58nk3d 
       foreign key (direccion_id) 
       references direccion;

    alter table if exists reserva 
       add constraint FKtr5bg864m3dseko7gif2bl239 
       foreign key (habitacion_id) 
       references habitacion;

    alter table if exists reserva 
       add constraint FK4cmijq3mjvu3ug5gwq2nkrjb3 
       foreign key (responsable_id) 
       references pasajero;
